### ISSUE TITLE
Output directory confusion

### ISSUE THREAD

**Issue by P-DR0ZD** [liutng/SSGifier#2]
Trying to use the -o or the --output command gives me the ```Input file is necessary to be provided.``` error however I'm unsure about formatting how am I supposed to pass the arguments so that the output directory is changed? I also checked the readme but the documentation for that doesn't show me an example

**Comment by liutng** [comment]
Fixed in commit [46c43a5](https://github.com/liutng/SSGifier/commit/46c43a51691214226a9452aacf7cd7897d5586e8)
