### ISSUE TITLE
Lab 2 Markdown Support

### ISSUE THREAD

**Issue by P-DR0ZD** [liutng/SSGifier#7]
I want to add markdown support to your project I will add the two features of Headings and Italics. To do this I will create two new functions that mirror ones you have already made but add markdown support so that when They need to be used instead of text documents they will

**Comment by liutng** [comment]
Implemented with commit [c17aa1db371d8f15d85fec7ae86b0743df0464d7](https://github.com/liutng/SSGifier/commit/c17aa1db371d8f15d85fec7ae86b0743df0464d7)

**Comment by liutng** [comment]
Issue reopened to add comments to the code and improve the document.

**Comment by liutng** [comment]
Feature implemented issue closed.
